# Generated by Django 3.1.3 on 2020-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Phone number')),
                ('destination', models.CharField(max_length=250, null=True, verbose_name='Destination')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
